-- CreateEnum
CREATE TYPE "TournamentFormatType" AS ENUM ('SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'MATCH_PLAY', 'BEST_GAME', 'CARD_QUALIFYING', 'PIN_GOLF', 'FLIP_FRENZY', 'STRIKE_FORMAT', 'TARGET_MATCH_PLAY', 'HYBRID', 'NONE');

-- AlterTable
ALTER TABLE "Tournament" ADD COLUMN "qualifyingFormat" "TournamentFormatType" NOT NULL DEFAULT 'NONE';
