# =============================================================================
# OPPR Production Environment Configuration
# Generated by Terraform - DO NOT EDIT MANUALLY
# =============================================================================

# Domain Configuration
DOMAIN=${domain}

# PostgreSQL Configuration
POSTGRES_PASSWORD=${postgres_password}

# API Configuration
NODE_ENV=production
LOG_LEVEL=info

# Frontend Configuration
# Empty for production (uses relative paths behind Caddy)
NEXT_PUBLIC_API_URL=

# JWT Configuration
JWT_SECRET=${jwt_secret}
JWT_REFRESH_SECRET=${jwt_refresh_secret}
JWT_ACCESS_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# Database Migration
# Migrations are run explicitly in CI/CD before deployment
RUN_MIGRATIONS=false
SEED_DATABASE=false
