import type { FastifyPluginAsync } from 'fastify';
import { authRoutes } from './auth.js';
import { playerRoutes } from './players.js';
import { tournamentRoutes } from './tournaments.js';
import { roundRoutes } from './rounds.js';
import { matchRoutes } from './matches.js';
import { entryRoutes } from './entries.js';
import { standingRoutes } from './standings.js';
import { statsRoutes } from './stats.js';
import { importRoutes } from './import.js';
import { userRoutes } from './users.js';
import { locationRoutes } from './locations.js';
import { blogPostRoutes } from './blog-posts.js';
import { blogTagRoutes } from './blog-tags.js';
import { apiKeyRoutes } from './api-keys.js';

export const v1Routes: FastifyPluginAsync = async (app) => {
  await app.register(authRoutes, { prefix: '/auth' });
  await app.register(playerRoutes, { prefix: '/players' });
  await app.register(tournamentRoutes, { prefix: '/tournaments' });
  await app.register(roundRoutes, { prefix: '/rounds' });
  await app.register(matchRoutes, { prefix: '/matches' });
  await app.register(entryRoutes, { prefix: '/entries' });
  await app.register(standingRoutes, { prefix: '/standings' });
  await app.register(statsRoutes, { prefix: '/stats' });
  await app.register(importRoutes, { prefix: '/import' });
  await app.register(userRoutes, { prefix: '/users' });
  await app.register(locationRoutes, { prefix: '/locations' });
  await app.register(blogPostRoutes, { prefix: '/blog-posts' });
  await app.register(blogTagRoutes, { prefix: '/blog-tags' });
  await app.register(apiKeyRoutes, { prefix: '/api-keys' });
};
